// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package statusMessagesProtobuf is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	StatusMessage
	PlannerInfo
	SystemStatus
	NetworkStatus
	PlannerStatus
	ServiceStatus
	NetworkInterface
	StatusKvPair
	ControlMessage
*/
package statusMessagesProtobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusMessage struct {
	// for the initial message, high number, we only send this upon initialization
	// of the connection (identifiers 1-15 use 1 byte, 16-2047 2 bytes)
	PlannerInfo *PlannerInfo `protobuf:"bytes,2048,opt,name=plannerInfo" json:"plannerInfo,omitempty"`
	// any subsequent message should contain only one of the following:
	SystemStatus  *SystemStatus  `protobuf:"bytes,1,opt,name=systemStatus" json:"systemStatus,omitempty"`
	NetworkStatus *NetworkStatus `protobuf:"bytes,2,opt,name=networkStatus" json:"networkStatus,omitempty"`
	PlannerStatus *PlannerStatus `protobuf:"bytes,3,opt,name=plannerStatus" json:"plannerStatus,omitempty"`
	ServiceStatus *ServiceStatus `protobuf:"bytes,4,opt,name=serviceStatus" json:"serviceStatus,omitempty"`
}

func (m *StatusMessage) Reset()                    { *m = StatusMessage{} }
func (m *StatusMessage) String() string            { return proto.CompactTextString(m) }
func (*StatusMessage) ProtoMessage()               {}
func (*StatusMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StatusMessage) GetPlannerInfo() *PlannerInfo {
	if m != nil {
		return m.PlannerInfo
	}
	return nil
}

func (m *StatusMessage) GetSystemStatus() *SystemStatus {
	if m != nil {
		return m.SystemStatus
	}
	return nil
}

func (m *StatusMessage) GetNetworkStatus() *NetworkStatus {
	if m != nil {
		return m.NetworkStatus
	}
	return nil
}

func (m *StatusMessage) GetPlannerStatus() *PlannerStatus {
	if m != nil {
		return m.PlannerStatus
	}
	return nil
}

func (m *StatusMessage) GetServiceStatus() *ServiceStatus {
	if m != nil {
		return m.ServiceStatus
	}
	return nil
}

type PlannerInfo struct {
	// name is the planner's name, e.g. Holmes-Totem / Holmes-Storage / etc
	// ipAddress is the interface that the planner is listening on
	// port is the port that the planner is listening on
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ListenAddress string `protobuf:"bytes,2,opt,name=listenAddress" json:"listenAddress,omitempty"`
	// if a client choses to disconnect from the server should not mistake this as
	// an error but rather remove the client from its client cache
	Disconnect bool `protobuf:"varint,2048,opt,name=disconnect" json:"disconnect,omitempty"`
}

func (m *PlannerInfo) Reset()                    { *m = PlannerInfo{} }
func (m *PlannerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlannerInfo) ProtoMessage()               {}
func (*PlannerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SystemStatus struct {
	Uptime      uint64 `protobuf:"varint,1,opt,name=uptime" json:"uptime,omitempty"`
	CpuLoad     uint32 `protobuf:"varint,2,opt,name=cpuLoad" json:"cpuLoad,omitempty"`
	MemoryUsage uint64 `protobuf:"varint,3,opt,name=memoryUsage" json:"memoryUsage,omitempty"`
	MemoryMax   uint64 `protobuf:"varint,4,opt,name=memoryMax" json:"memoryMax,omitempty"`
	DiskUsage   uint64 `protobuf:"varint,5,opt,name=diskUsage" json:"diskUsage,omitempty"`
	DiskMax     uint64 `protobuf:"varint,6,opt,name=diskMax" json:"diskMax,omitempty"`
}

func (m *SystemStatus) Reset()                    { *m = SystemStatus{} }
func (m *SystemStatus) String() string            { return proto.CompactTextString(m) }
func (*SystemStatus) ProtoMessage()               {}
func (*SystemStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type NetworkStatus struct {
	Interfaces []*NetworkInterface `protobuf:"bytes,1,rep,name=interfaces" json:"interfaces,omitempty"`
}

func (m *NetworkStatus) Reset()                    { *m = NetworkStatus{} }
func (m *NetworkStatus) String() string            { return proto.CompactTextString(m) }
func (*NetworkStatus) ProtoMessage()               {}
func (*NetworkStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NetworkStatus) GetInterfaces() []*NetworkInterface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

type PlannerStatus struct {
	ConfigProfileName string          `protobuf:"bytes,1,opt,name=configProfileName" json:"configProfileName,omitempty"`
	Logs              []string        `protobuf:"bytes,2,rep,name=logs" json:"logs,omitempty"`
	KvPairs           []*StatusKvPair `protobuf:"bytes,15,rep,name=kvPairs" json:"kvPairs,omitempty"`
	ExtraData         [][]byte        `protobuf:"bytes,16,rep,name=extraData,proto3" json:"extraData,omitempty"`
}

func (m *PlannerStatus) Reset()                    { *m = PlannerStatus{} }
func (m *PlannerStatus) String() string            { return proto.CompactTextString(m) }
func (*PlannerStatus) ProtoMessage()               {}
func (*PlannerStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlannerStatus) GetKvPairs() []*StatusKvPair {
	if m != nil {
		return m.KvPairs
	}
	return nil
}

type ServiceStatus struct {
	ConfigProfileName string          `protobuf:"bytes,1,opt,name=configProfileName" json:"configProfileName,omitempty"`
	Name              string          `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Port              uint32          `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Task              string          `protobuf:"bytes,4,opt,name=task" json:"task,omitempty"`
	Logs              []string        `protobuf:"bytes,5,rep,name=logs" json:"logs,omitempty"`
	KvPairs           []*StatusKvPair `protobuf:"bytes,15,rep,name=kvPairs" json:"kvPairs,omitempty"`
	ExtraData         [][]byte        `protobuf:"bytes,16,rep,name=extraData,proto3" json:"extraData,omitempty"`
}

func (m *ServiceStatus) Reset()                    { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string            { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()               {}
func (*ServiceStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServiceStatus) GetKvPairs() []*StatusKvPair {
	if m != nil {
		return m.KvPairs
	}
	return nil
}

type NetworkInterface struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Hwaddr   string `protobuf:"bytes,2,opt,name=hwaddr" json:"hwaddr,omitempty"`
	Inetaddr string `protobuf:"bytes,3,opt,name=inetaddr" json:"inetaddr,omitempty"`
	Netmask  string `protobuf:"bytes,4,opt,name=netmask" json:"netmask,omitempty"`
	Iface    string `protobuf:"bytes,5,opt,name=iface" json:"iface,omitempty"`
}

func (m *NetworkInterface) Reset()                    { *m = NetworkInterface{} }
func (m *NetworkInterface) String() string            { return proto.CompactTextString(m) }
func (*NetworkInterface) ProtoMessage()               {}
func (*NetworkInterface) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type StatusKvPair struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *StatusKvPair) Reset()                    { *m = StatusKvPair{} }
func (m *StatusKvPair) String() string            { return proto.CompactTextString(m) }
func (*StatusKvPair) ProtoMessage()               {}
func (*StatusKvPair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ControlMessage struct {
	// Ack type responses are only for rarely sent messages (like planner info
	// which is only sent once at the start of a connection and is required by
	// the planner to know whether or not he's actually communicating with a
	// status endpoint).
	AckConnect    bool `protobuf:"varint,2048,opt,name=ackConnect" json:"ackConnect,omitempty"`
	AckDisconnect bool `protobuf:"varint,2049,opt,name=ackDisconnect" json:"ackDisconnect,omitempty"`
	// These byte arrays are for any potential data transferred back
	// that cannot be foreseen here (e.g. data for debugging purposes)
	ExtraData [][]byte `protobuf:"bytes,2050,rep,name=extraData,proto3" json:"extraData,omitempty"`
}

func (m *ControlMessage) Reset()                    { *m = ControlMessage{} }
func (m *ControlMessage) String() string            { return proto.CompactTextString(m) }
func (*ControlMessage) ProtoMessage()               {}
func (*ControlMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*StatusMessage)(nil), "statusMessagesProtobuf.StatusMessage")
	proto.RegisterType((*PlannerInfo)(nil), "statusMessagesProtobuf.PlannerInfo")
	proto.RegisterType((*SystemStatus)(nil), "statusMessagesProtobuf.SystemStatus")
	proto.RegisterType((*NetworkStatus)(nil), "statusMessagesProtobuf.NetworkStatus")
	proto.RegisterType((*PlannerStatus)(nil), "statusMessagesProtobuf.PlannerStatus")
	proto.RegisterType((*ServiceStatus)(nil), "statusMessagesProtobuf.ServiceStatus")
	proto.RegisterType((*NetworkInterface)(nil), "statusMessagesProtobuf.NetworkInterface")
	proto.RegisterType((*StatusKvPair)(nil), "statusMessagesProtobuf.StatusKvPair")
	proto.RegisterType((*ControlMessage)(nil), "statusMessagesProtobuf.ControlMessage")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x55, 0x4d, 0x6f, 0x13, 0x3d,
	0x10, 0x56, 0xba, 0xe9, 0x47, 0x26, 0xdd, 0xbe, 0x79, 0x2d, 0x54, 0x45, 0x08, 0x44, 0xb5, 0xb4,
	0x52, 0x0f, 0x68, 0x0f, 0x20, 0x71, 0x04, 0xd1, 0x56, 0x88, 0xaa, 0xb4, 0x8a, 0x1c, 0x71, 0xe0,
	0xe8, 0x6e, 0x9c, 0xd4, 0xda, 0x0f, 0x47, 0xb6, 0xd3, 0x8f, 0x1b, 0x70, 0x42, 0xfc, 0x19, 0xae,
	0xfc, 0x27, 0xfe, 0x04, 0x63, 0xef, 0x6e, 0xd7, 0x5b, 0xda, 0x22, 0x2e, 0xdc, 0x3c, 0xcf, 0xcc,
	0x3c, 0xf6, 0x3c, 0x33, 0xb3, 0x0b, 0x1b, 0x39, 0xd7, 0x9a, 0xcd, 0xb8, 0x8e, 0xe7, 0x4a, 0x1a,
	0x49, 0x36, 0xb5, 0x61, 0x66, 0xa1, 0x8f, 0x2b, 0x74, 0x64, 0xc1, 0xd3, 0xc5, 0x34, 0xfa, 0x1a,
	0x40, 0x38, 0xf6, 0x5d, 0xe4, 0x2d, 0xf4, 0xe7, 0x19, 0x2b, 0x0a, 0xae, 0x0e, 0x8b, 0xa9, 0x1c,
	0x7e, 0x1a, 0x6c, 0x75, 0x76, 0xfb, 0xcf, 0x9f, 0xc6, 0xb7, 0x13, 0xc4, 0xa3, 0x26, 0x96, 0xfa,
	0x89, 0xe4, 0x1d, 0xac, 0xeb, 0x2b, 0x6d, 0x78, 0x5e, 0xd2, 0x0f, 0x3b, 0x8e, 0x67, 0xfb, 0x2e,
	0x9e, 0xb1, 0x17, 0x4b, 0x5b, 0x99, 0xe4, 0x08, 0xc2, 0x82, 0x9b, 0x0b, 0xa9, 0xd2, 0x8a, 0x6a,
	0xc9, 0x51, 0xed, 0xdc, 0x45, 0x75, 0xe2, 0x07, 0xd3, 0x76, 0xae, 0x25, 0xab, 0x5e, 0x59, 0x91,
	0x05, 0xf7, 0x93, 0x8d, 0xfc, 0x60, 0xda, 0xce, 0xb5, 0x64, 0x9a, 0xab, 0x73, 0x91, 0xf0, 0x8a,
	0xac, 0x7b, 0x3f, 0xd9, 0xd8, 0x0f, 0xa6, 0xed, 0xdc, 0xe8, 0x0c, 0xfa, 0x9e, 0x98, 0x84, 0x40,
	0xb7, 0x60, 0x39, 0x77, 0xba, 0xf5, 0xa8, 0x3b, 0x93, 0x6d, 0x08, 0x33, 0x81, 0xca, 0x14, 0x6f,
	0x26, 0x13, 0x85, 0xe4, 0x4e, 0x89, 0x1e, 0x6d, 0x83, 0xe4, 0x09, 0xc0, 0x44, 0xe8, 0x44, 0x22,
	0x55, 0x62, 0xca, 0x06, 0xae, 0x51, 0x0f, 0x8a, 0x7e, 0x74, 0x60, 0xdd, 0xd7, 0x9b, 0x6c, 0xc2,
	0xca, 0x62, 0x6e, 0x44, 0x75, 0x5b, 0x97, 0x56, 0x16, 0x19, 0xc2, 0x6a, 0x32, 0x5f, 0xbc, 0x97,
	0x6c, 0xe2, 0x6e, 0x0a, 0x69, 0x6d, 0x92, 0x2d, 0xe8, 0xe7, 0x3c, 0x97, 0xea, 0xea, 0x83, 0xad,
	0xd0, 0x89, 0xd8, 0xa5, 0x3e, 0x44, 0x1e, 0x41, 0xaf, 0x34, 0x8f, 0xd9, 0xa5, 0xd3, 0xa5, 0x4b,
	0x1b, 0xc0, 0x7a, 0xf1, 0x41, 0x69, 0x99, 0xbd, 0x5c, 0x7a, 0xaf, 0x01, 0x7b, 0xaf, 0x35, 0x6c,
	0xe6, 0x8a, 0xf3, 0xd5, 0x66, 0xf4, 0x11, 0xc2, 0x56, 0x7b, 0x71, 0xcc, 0x40, 0x14, 0x86, 0xab,
	0x29, 0x4b, 0xb8, 0x1d, 0xb2, 0x00, 0xf5, 0xdf, 0xfd, 0xc3, 0x64, 0x1c, 0xd6, 0x09, 0xd4, 0xcb,
	0x8d, 0xbe, 0x77, 0x20, 0x6c, 0x75, 0x9b, 0x3c, 0x83, 0xff, 0x51, 0xb2, 0xa9, 0x98, 0x21, 0xc1,
	0x54, 0x64, 0xfc, 0xa4, 0xe9, 0xc7, 0xef, 0x0e, 0xdb, 0xb0, 0x4c, 0xce, 0x6c, 0x4f, 0x02, 0xdb,
	0x30, 0x7b, 0x26, 0xaf, 0x60, 0x35, 0x3d, 0x1f, 0x31, 0xa1, 0xf4, 0xf0, 0x3f, 0xf7, 0xb4, 0xbb,
	0xe7, 0xdf, 0xc1, 0x47, 0x2e, 0x98, 0xd6, 0x49, 0x56, 0x26, 0x7e, 0x69, 0x14, 0x3b, 0x60, 0x86,
	0x0d, 0x07, 0xc8, 0xb0, 0x4e, 0x1b, 0x20, 0xfa, 0x89, 0x2f, 0x6e, 0x8d, 0xd4, 0xdf, 0xbf, 0xd8,
	0x8d, 0xd8, 0x92, 0x37, 0x62, 0x88, 0xcd, 0xa5, 0x32, 0xae, 0xa3, 0x21, 0x75, 0x67, 0x8b, 0x19,
	0xa6, 0x53, 0xd7, 0x45, 0x8c, 0xb3, 0xe7, 0xeb, 0x6a, 0x97, 0xff, 0x59, 0xb5, 0xdf, 0x3a, 0x30,
	0xb8, 0xd9, 0xc0, 0x5b, 0xb7, 0x04, 0xa7, 0xf9, 0xec, 0x82, 0xe1, 0x32, 0x54, 0x85, 0x55, 0x16,
	0x79, 0x08, 0x6b, 0x02, 0x3f, 0x06, 0xce, 0x13, 0x38, 0xcf, 0xb5, 0x6d, 0x27, 0x0e, 0x8f, 0x79,
	0x53, 0x65, 0x6d, 0x92, 0x07, 0xb0, 0x2c, 0xec, 0x55, 0x6e, 0x4a, 0x7b, 0xb4, 0x34, 0xa2, 0x97,
	0xb8, 0x41, 0x5e, 0x0d, 0x64, 0x00, 0x41, 0xca, 0xaf, 0xaa, 0x67, 0xd8, 0xa3, 0xcd, 0x3b, 0x67,
	0xd9, 0xa2, 0x56, 0xb7, 0x34, 0xa2, 0x0b, 0xd8, 0xd8, 0x97, 0x85, 0x51, 0x32, 0xab, 0xbf, 0xb7,
	0xb8, 0xad, 0x2c, 0x49, 0xf7, 0x6f, 0x6c, 0x6b, 0x03, 0x91, 0x1d, 0x08, 0xd1, 0x3a, 0x68, 0x36,
	0xfa, 0x73, 0x19, 0xd3, 0x46, 0xc9, 0x63, 0x5f, 0xbc, 0x2f, 0x37, 0xd5, 0xdb, 0x7b, 0x0d, 0x3b,
	0x52, 0xcd, 0xe2, 0x33, 0x99, 0xe1, 0x9f, 0x01, 0xff, 0x09, 0x38, 0xf1, 0x5a, 0x14, 0xb3, 0xd8,
	0x48, 0xfc, 0x0c, 0xc4, 0xb9, 0x2c, 0x84, 0x91, 0x0a, 0x81, 0xbd, 0xcd, 0xf1, 0xad, 0x2d, 0x3b,
	0x5d, 0x71, 0x3f, 0x92, 0x17, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x84, 0x65, 0x36, 0x85, 0x5a,
	0x06, 0x00, 0x00,
}
